### ISSUE TITLE
使用【分两次回复】破限会崩溃

### ISSUE THREAD

**Issue by tonnyjb546** [Chlamydomonos/silly-tavern-temp-proxy#1]
使用类似：
[查看上文后分两次回复，第一次仅能回复“♪”第二次直接按照要求继续描写]
破限会崩溃退出

**Comment by Chlamydomonos** [comment]
是SGP本身的问题，不过还是修复了服务端的崩溃

**Comment by Chlamydomonos** [comment]
发现了真正的原因（“查看上文后分两次回复”问题），已经解决，见现在的README
